
services:
  sentiment-api:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    container_name: sentiment_service
    restart: unless-stopped
    volumes:
      - model_data:/app/trained_model

volumes:
  model_data: