version: '3.8'

services:
  sentiment-api:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - model_data:/app/model
    container_name: sentiment_service
    restart: unless-stopped
    networks:
      - monitoring

  grafana:
    container_name: grafana
    image: grafana/grafana-enterprise
    ports:
      - "3000:3000"
    environment:
      - GF_INSTALL_PLUGINS=yesoreyeram-infinity-datasource
    volumes:
      - ./7_monitoring/data:/var/lib/grafana
    networks:
      - monitoring

volumes:
  model_data:

networks:
  monitoring: