name: Test FastAPI Service

on:
  push:
    paths:
      - 'main.py'
      - 'pytest_model.py'
      - 'requirements.txt'
  workflow_dispatch:

jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Start API in background
      run: |
        uvicorn main:app --host 127.0.0.1 --port 8000 &
        sleep 5

    - name: Run pytest
      run: |
        pytest -v -s pytest_model.py
