name: Train Model

on:
  push:
    paths:
      - 'app/train.py'
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        cd app
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip uninstall -y transformers
        pip install transformers>=4.30.0
        
    - name: Prepare directories
      run: |
        cd app
        mkdir -p model logs results
        
    - name: Run training
      run: |
        cd app
        python train.py
